version: "3"

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    environment:
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=dvwa
    restart: always

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "8082:3000"
    restart: always
